config/routes.rb
Rails.application.routes.draw do
  get 'pages#x'

  get 'pages#y'

  post 'pages#save_form'

  get 'pages#landing'

  get 'pages#see_users'

  root 'pages#landing'

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def x
  end

  def y
      @usuarios = Usuario.all
  end

  def landing

    render layout: "layout2"
  end

  def see_users
  end

  def save_form

    Usuario.create(name: params[:q], email: params[:l], age: params[:m])
    redirect_to pages_y_path, notice: "El usuario fue guardado"

  end

def see_users

  @usuarios = Usuario.all

end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Practicapre</title>
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


<%= yield %>

</body>
</html>

app/views/layouts/layout2.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Practicapre</title>
    <%= stylesheet_link_tag  'bootstrap', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag  'creative', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'bootstrap' %>
    <%= javascript_include_tag 'creative'%>



<%= yield %>

</body>
</html>

app/views/pages/landing.html.erb
<body id="page-top" class="bg-dark">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">Ejercicio 40</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="/pages/x">Pag X</a>
                    </li>
                
                    <li>
                        <a class="page-scroll" href="/pages/see_users">Ver Usuarios</a>
                    </li>

                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <header>
        <div class="header-content">
            <div class="header-content-inner">
              <h1>          :D                       </h1>
                <h1 id="homeHeading">Landing: EJERCICIO 40 </h1>
                <hr>
                <p> axel antonio lópez loza
                </p>
            </div>
        </div>
    </header>

app/views/pages/see_users.html.erb
<h2> Usuarios registrados: </h2>
<% @usuarios.each do |x,l,m| %>
<p> <%= x.name %> </p>
<p> <%= x.email%> </p>
<p> <%= x.age %> </p>
<% end%>

app/views/pages/x.html.erb
<h1>Axel Antonio López Loza </h1>
<p>Find me in app/views/pages/x.html.erb</p>
<form action="<%= pages_save_form_path %>" method="POST">
  <%= hidden_field_tag :authenticity_token,
form_authenticity_token %>
    <input placeholder="Nombre" name="q">
    <input placeholder="E-mail" email="l">
    <input placeholder="Edad" age="m">
    <input type="submit" value="Enviar">

  </form>

app/views/pages/y.html.erb
<h1><%= notice %></h1>
<h2>
  Vuelve Pronto
</h2>